content_file: "markdown/list"
data_api_mesh:
  - 
    - 
      api_id: "goapi/base_object_list"
      params:
        tag: "@_root.tag/@nil"
        _page: "@_root._page/1"
        _page_size: "@_root._page_size/20"
      as: "list_data"
    - 
      api_id: "goapi/base_object_distinct"
      params:
        _field: "tag"
      as: "tag_list"
type: "vue"
default_params:
title: "文章列表"