port: 8888
env: "develop"
resource_dir: "./resource"
page_conf_dir: "./config/page"
api_conf_dir: "./config/api"
default_frame_file: "frame/default.html"
public_file_extension:
  css: "text/css"
  js: "application/javascript"
  ttf: "application/octet-stream"
  
