tag: "文章"
list:
  list:
    content_file: "markdown/list.html"
    data_api: "goweb/api_v1_list_object"
    type: "vue"
    href_title: "文章列表"
    default_params:
      abc: "abc"
    extension:
      keys:
        - aaa
        - bbb
    title: ""