product: &product
  driver: "mysql"
  write_host: "xxx"
  read_host: "xxx"
  write_user: "root"
  write_password: "xxx"
  read_user: "root"
  read_password: "xxx"
  database: "xx"
  charset: "utf8mb4"
  collation: "utf8mb4_general_ci"

develop:
  <<: *product