base_uri:
  default: "http://localhost:9000"
  test: "http://192.168.3.88:8888"

timeout: 10000
sign_alg: "test"
success_code: "0"
code_key: "code"
message_key: "message"
data_key: "data"
header:
  source: "alliance"

api:
  base_object_list:
    path: "database/base/list/object"
    method: "GET"
  base_object_query:
    path: "database/base/query/object"
    method: "GET"
  base_object_distinct:
    path: "database/base/distinct/object"
    method: "GET"
  base_object_create:
    path: "database/base/create/object"
    method: "POST"
    content_type: "application/json"
  base_object_update:
    path: "database/base/update/object"
    method: "POST"
    content_type: "application/json"
  base_object_delete:
    path: "database/base/delete/object"
    method: "POST"
    content_type: "application/json"
  base_tables:
    path: "database/base/tables"
    method: "GET"
  base_exec_sql:
    path: "database/base/exec/sql"
    method: "POST"
    content_type: "application/json"
  base_code_list:
    path: "database/base/list/code"
    method: "GET"
  base_code_create:
    path: "database/base/create/code"
    method: "POST"
    content_type: "application/json"
