base_uri:
  default: "http://192.168.3.88:8888"
  test: "http://192.168.3.88:8888"

timeout: 10000
sign_alg: "test"
success_code: "0"
code_key: "code"
message_key: "status"
data_key: "data"
header:
  source: "alliance"

api:
  api_v1_base_list_object:
    path: "database/base/list/object"
    method: "GET"
  api_v1_base_query_object:
    path: "database/base/query/object"
    method: "GET"
  api_v1_base_distinct_object:
    path: "database/base/distinct/object"
    method: "GET"
